### Nick Komlanc
### Assignment 6
### Version 1
### Fall 2020

In [3]:
import numpy as np

1a)

In [4]:
arr = np.array([[10, 20], [30, 40]])

In [5]:
arr

array([[10, 20],
       [30, 40]])

In [6]:
np.square(arr)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [7]:
new_arr=arr+100

In [8]:
new_arr

array([[110, 120],
       [130, 140]])

In [9]:
mult_arr=arr*5

In [10]:
mult_arr

array([[ 50, 100],
       [150, 200]])

In [11]:
np.sqrt(arr)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

1b)

In [20]:
three_1=np.arange(3, 28, 3)

In [21]:
three_1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [33]:
three_2=np.arange(10,20,1.2)

In [34]:
three_2

array([10. , 11.2, 12.4, 13.6, 14.8, 16. , 17.2, 18.4, 19.6])

In [35]:
mult_b=three_2*three_1

In [36]:
mult_b

array([ 30. ,  67.2, 111.6, 163.2, 222. , 288. , 361.2, 441.6, 529.2])

1c)

In [42]:
a=np.array([52,12,81,0,58])
b=np.array([96,4,61,16,43])
c=np.array([38,96,45,17,58])
d=np.array([97,21,22,25,6])
e=np.array([77,6,19,2,74])
abcde_stack=np.stack((a,b,c,d,e),0)

In [44]:
abcde_stack

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])